### ISSUE TITLE
user should easily be able to check for null values across all variables

### ISSUE THREAD

**Issue by nswitanek** [teradata-aster-field/toaster#14]
Write simple wrapper function for common task of checking for null values across all columns of Aster table.

**Comment by grigory93** [comment]
How about this spec:
name: getNullCounts
parameters: channel, tableName, include=NULL, except=NULL, where=NULL, test=FALSE
belongs to: utils.R
complies with _getTableSummary_ by following the same conventions on parameters and tests
visibility: exported
implementation: single sql call counting number of rows, null counts per column (for those specified specified  or by default all)
output: raw counts or/and percent of nulls

By the way, you can run _getTableSummary_ and extract NULL counts from its result but it's way more expensive since there is more stuff going on so each column is calculated separately.
In fact, I was looking at its code (_getTableSummary_) and realized that it could be optimized to run for all columns at once - but it was too much coding to do...

**Comment by grigory93** [comment]
One more convention to follow (it's now when I am working on new function for kmeans I am refreshing my memory): parameter _tableInfo_ is used to circumvent call to _sqlColumns_ (extra database call). Actually, it's not that expensive but this parameter plays key role in tests so it has dual purpose. 

Let me explain. In real use case user may run _getTableSummary_ and save results into _table_info_ variable. Then any function that has _tableInfo_ parameter will accept it and won't run _sqlColumns_ using passed _table_info_ instead. For example see _computeCorrelations_, _computeHistogram_). 

But real value comes in tests that check generated sql (no live database). So it can't run _sqlColumns_ either. Instead they pass pre-built _table_info_ object and functions won't need to go to a database to list columns (see **test-computeCorrelations.R**, **test-computeHistograms.R**).

Now, when I design _computeKmeans_ function I use _tableInfo_ parameter exactly as described... Hope all these didn't put asleep.

Also, I believe that instead of running rather time consuming _getTableSummary_ you can use result of **RODBC** native _sqlColumns_, save it to _table_info_ once and then use across multiple calls.

**Comment by nswitanek** [comment]
Thanks for the comments, Gregory. I believe that means the following to-do items:
- [ ] change function to match gregory's proposed spec
- [ ] move function from separate script into utils.R
- [ ] use sqlColumns from RODBC
- [ ] add tableInfo parameter (saving result of sqlColumns to tableInfo if not exists)

For performance improvement, it'd be nice to also do the following:
- [ ] adjust code so that all column null counts are run at once

I'll copy these items to the corresponding pull request, which is where the commits closing each to-do item will be easily tracked.

**Comment by grigory93** [comment]
merged count-column-nulls branch into develop
